### ISSUE TITLE
ValueError: format not resolved, probably missing URL scheme or undefined destination target for '157641'

### ISSUE THREAD

**Issue by rbouma** [teticio/kindle2pdf#4]
I tried it with one kindle but got this exception:

```bash
kindle2pdf B08R3Y6NTC
100%|█████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 549329/549329 [04:11<00:00, 2185.50it/s]
Traceback (most recent call last):
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/bin/kindle2pdf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/src/kindle2pdf.py", line 479, in main
    output_path = kindle2pdf.render_book(output_path=args.output)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/src/kindle2pdf.py", line 448, in render_book
    pdf_canvas.save()
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfgen/canvas.py", line 1299, in save
    self._doc.SaveToFile(self._filename, self)
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 212, in SaveToFile
    data = self.GetPDFData(canvas)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 238, in GetPDFData
    return self.format()
           ^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 420, in format
    IOf = IO.format(self)
          ^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 867, in format
    fcontent = format(self.content, document, toplevel=1)   # yes this is at top level
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 67, in format
    f = element.format(document)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 1633, in format
    return D.format(document)
           ^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 680, in format
    L = [(format(PDFName(k),document)+b" "+format(dict[k],document)) for k in keys]
                                           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 67, in format
    f = element.format(document)
        ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Volumes/Development/Modules/Python/kindle2pdf/env/lib/python3.12/site-packages/reportlab/pdfbase/pdfdoc.py", line 1797, in format
    if f is None: raise ValueError("format not resolved, probably missing URL scheme or undefined destination target for '%s'" % self.name)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: format not resolved, probably missing URL scheme or undefined destination target for '157641'
```

Upon more inspection in the code on https://github.com/teticio/kindle2pdf/blob/e2832c8b212349d1e76fec4f69bc7051ec5afe0d/src/kindle2pdf.py#L391-L396

Replaced this code with this:

```python
if "link" in child and child["link"]["linkPositionId"] < book_end_pos:
    pdf_canvas.linkAbsolute(
        contents="",
        destinationname=child["link"]["linkPositionId"],
        Rect=(x, y, x + width, y + height),
    )
else:
    logger.warning("Invalid link found: %s", child)
```

and output was:
```
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 117.5326, 377.0], 'elementId': 2191, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 351.28125}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 351.28125, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 117.5326, 437.0], 'elementId': 2193, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 454.671875}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 454.671875, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 80.0, 554.0], 'elementId': 2195, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 656.125}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 656.125, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 117.5326, 614.0], 'elementId': 2197, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 404.71875}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 404.71875, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 117.5326, 674.0], 'elementId': 2199, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 431.34375}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 431.34375, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 117.5326, 734.0], 'elementId': 2201, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 375.265625}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 375.265625, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}
Invalid link found: {'type': 'textline', 'transform': [1.0, 0.0, 0.0, 1.0, 80.0, 851.00003], 'elementId': 2203, 'rect': {'top': 0.0, 'left': 0.0, 'bottom': 49.0, 'right': 842.875}, 'backDecoration': [{'type': 'linkLine', 'backgroundColor': '#ffffffff', 'strokeStartPoint': {'x': 0.0, 'y': 39.805335}, 'strokeEndPoint': {'x': 842.875, 'y': 39.805335}, 'strokeWidth': 1.906666, 'strokeColor': '#0000ffff', 'strokeStyle': 'solid', 'visitedColor': '#0000ffff', 'unvisitedColor': '#0000ffff'}], 'ascent': 31.005334, 'descent': -7.656, 'lineHeight': 49.0, 'baseLine': 36.417335}

```

Replaced it to skip these for now so i can have the pdf file with: 

```python
 # Check if 'link' exists in the child dictionary
if "link" in child:
    link_position_id = child["link"].get("linkPositionId")

    # Validate the link_position_id
    if link_position_id is not None:
        if link_position_id < book_end_pos:
            pdf_canvas.linkAbsolute(
                contents="",
                destinationname=link_position_id,
                Rect=(x, y, x + width, y + height),
            )
        else:
            continue  # Skip to the next child if the link is invalid
    else:
        continue  # Skip to the next child if linkPositionId is None
```

**Comment by avirakesh** [comment]
Dug into this a little bit more, and the main issue seems to be from the unconditional `start_pos += 1` after the ` pdf_canvas.bookmarkPage(start_pos)` calls. 

The problematic block is:
https://github.com/teticio/kindle2pdf/blob/e2832c8b212349d1e76fec4f69bc7051ec5afe0d/src/kindle2pdf.py#L338-L340

On inspecting `children` objects, I realized that sometimes, the `child["startPositingId"]` is smaller than previous page's `endPositionId`, which means the loop is never executed. This is fine by itself (logically), but statement `start_pos += 1` in cases where the loop doesn't execute skips a value of `start_pos` which never gets bookmarked. 

 If a link somewhere happens to reference one of the skipped IDs, the failure looks like the original comment. 

Here's a quick patch to print out values where the loop isn't run (which are the IDs that are never bookmarked), but `start_pos` is  incremented anyway.

```patch
diff --git a/src/kindle2pdf.py b/src/kindle2pdf.py
index 24599c3..37603f7 100644
--- a/src/kindle2pdf.py
+++ b/src/kindle2pdf.py
@@ -335,6 +335,10 @@ class Kindle2PDF:
         for page in pages:
             for child in page["children"]:
                 if "startPositionId" in child:
+                    if start_pos > child["startPositionId"]:
+                        print(
+                            f"start_pos({start_pos}) > child.startPositionId({child['startPositionId']})"
+                        )
                     for start_pos in range(start_pos, child["startPositionId"] + 1):
                         pdf_canvas.bookmarkPage(start_pos)
                     start_pos += 1
@@ -396,6 +400,8 @@ class Kindle2PDF:
                     )
 
             end_pos = page["endPositionId"]
+            if start_pos > end_pos:
+                print(f"start_pos({start_pos}) > end_pos({end_pos})")
             for start_pos in range(start_pos, end_pos + 1):
                 pdf_canvas.bookmarkPage(start_pos)
             start_pos += 1

```

I was trying this with ASIN `B0CCNBQ2HS` if you want to repro the issue. 

I am not super familiar with the encodings here, or if it is valid for `child["startPositionId"] to be less than `page["endPositionId"]`, but the simple solution to this specific issue is to only increment `start_pos` if the loop was entered.

**Comment by teticio** [comment]
Hi! Thanks for reporting this issue and thanks @avirakesh for fixing it so quickly! it's difficult for me to test with books I don't own, so I would greatly appreciate it @rbouma if you could grab the latest version and test it on your PDF, even though you managed to find a workaround.

**Comment by rbouma** [comment]
@teticio I can confirm the changed done by @avirakesh is working. Thanks for the quick fixing

**Comment by teticio** [comment]
@rbouma Thanks for the quick testing!

**Comment by teticio** [comment]
Btw the PR change was slightly different to the above code.

**Comment by rbouma** [comment]
@teticio I already saw it was different and tested the PR. Thanks for merging :)
