### ISSUE TITLE
No access to browser cookies

### ISSUE THREAD

**Issue by JanOwiesniak** [teticio/kindle2pdf#7]
**System**

macOS Version 13.6 (22G120)
Chrome Version 129.0.6668.101

**Issue**

I logged in with my Amazon credentials on https://read.amazon.com but it seems like `requests.utils.dict_from_cookiejar(cookies)` returns an empty array.

<img width="877" alt="chrome-cookies" src="https://github.com/user-attachments/assets/9d948544-5af3-46b2-8689-2b4c7d177d13">

**run pip package**

```
kindle2pdf B084514TDV                           
Traceback (most recent call last):
  File "/opt/homebrew/bin/kindle2pdf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 502, in main
    kindle2pdf = Kindle2PDF(
                 ^^^^^^^^^^^
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 89, in __init__
    self.session = self.start_reading_session()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 102, in start_reading_session
    "x-amzn-sessionid": requests.utils.dict_from_cookiejar(cookies)[
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'session-id'
```

**ran source code**

```
python3 -m src.kindle2pdf B084514TDV            
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 518, in <module>
    sys.exit(main())
             ^^^^^^
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 502, in main
    kindle2pdf = Kindle2PDF(
                 ^^^^^^^^^^^
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 89, in __init__
    self.session = self.start_reading_session()
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/jan/Code/kindle2pdf/src/kindle2pdf.py", line 102, in start_reading_session
    "x-amzn-sessionid": requests.utils.dict_from_cookiejar(cookies)[
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'session-id'
```

**Comment by teticio** [comment]
Although now I think of it, there may be other cookies required. Will check.

**Comment by teticio** [comment]
Nah, sorry, a boringly large number of cookies are required.

**Comment by teticio** [comment]
It might be related to https://github.com/borisbabic/browser_cookie3/issues/210
